### ISSUE TITLE
[FR] exporter interface

### ISSUE THREAD

**Issue by jiekun** [deepflowio/deepflow#3926]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

DeepFlow has implemented OTLP Exporter. But it's an exporter instance, not an interface.

I suggest refactor the implementation of the current flow_log exporter (which include OTLP exporter only) to provide an extendable interface. So new exporter impls could be easily added as a plugin.

### Use case

N/A

### Related issues

N/A

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jiekun** [comment]
I'm proposing new config layout for exporter part:
```yaml
  exporters:
    - name: default otlp exporter
      type: otlp-exporter
      otlp-exporter:
        enabled: false
        addr: 127.0.0.1:4317
        ... # other config belongs to otlp-exporter
    - name: second exporter
      type: loki-exporter
      loki-exporter:
        addr: 127.0.0.1:12345
        format: bla bla bla
        ... # other config belongs to loki-exporter
```
