### ISSUE TITLE
[BUG] Missing service name

### ISSUE THREAD

**Issue by jiekun** [deepflowio/deepflow#3989]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

I am using OTLP exporter with the following config to tempo:
```yaml
    ingester:
      otlp-exporter:
        enabled: true
        addr: tempo.tempo.svc.cluster.local:4317
        export-datas: [ebpf-sys-span, otel-app-span]
        export-data-types: [ service_info,tracing_info,network_layer,flow_info,transport_layer,application_layer,metrics ]
        queue-count: 4
        queue-size: 100000
        export-custom-k8s-labels-regexp:
        export-only-with-traceid: true
        export-batch-count: 32
```
And grabbing data generated by the official demo of OpenTelemetry:
```bash
helm install my-otel-demo open-telemetry/opentelemetry-demo
```
However, I cannot see any service name in the dropbox in Tempo.
![image](https://github.com/deepflowio/deepflow/assets/30280396/a5c4207b-e41b-44a4-a91e-0ca7ed941771)

**Query by Span Name and TraceID are available with correct result, which means trace data are exported.**

### How to reproduce

1. deploy tempo
2. deploy DeepFlow with OTLP exporter
3. deploy OTEL Demo
4. Query tempo with Grafana

### DeepFlow version

self-builded from `main` branch.

### DeepFlow agent list

self-builded from `main` branch.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
