### ISSUE TITLE
[BUG] 修改deepflow-server的server.yaml文件后，pod重启失败。

### ISSUE THREAD

**Issue by mcy567** [deepflowio/deepflow#4226]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

最近在测试 [输出至 OpenTelemetry Collector](https://deepflow.io/docs/zh/server-integration/export/opentelemetry-collector/) 的功能，当我修改configmap(deepflow)添加 exporters: 相关字段并删除pod（deepflow-server）后，pod无法正常启动。

pod日志如下：
```
2023-09-12 17:35:56.572 [INFO] [labeler] labeler_manager.go:212 Start labeler manager
2023-09-12 17:35:56.572 [INFO] [trident_adapter] trident_adapter.go:300 Start trident adapter
2023-09-12 17:35:56.572 [ERRO] [flow_log.config] config.go:136 Unmarshal yaml error: yaml: unmarshal errors:
  line 41: cannot unmarshal !!map into []exporter.ExporterCfg
```
截图如下：
![image](https://github.com/deepflowio/deepflow/assets/22673808/613915a8-eb2a-49af-a4b5-2bdc7ec6242f)

### How to reproduce

1. 安装deepflow：
参考 https://deepflow.io/docs/zh/install/all-in-one/

2. 修改configmap
```kubectl edit configmap deepflow -n deepflow```

3. 添加 如下配置到 ingester下
```yaml
  exporters:
    enabled: true
    export-datas: [cbpf-net-span,ebpf-sys-span]
    export-data-types: [service_info,tracing_info,network_layer,flow_info,transport_layer,application_layer,metrics]
    export-custom-k8s-labels-regexp:
    export-only-with-traceid: false
    otlp-exporters:
    - enabled: true
      addr: 192.168.42.252:4317
      queue-count: 4
      queue-size: 1000000
      export-batch-count: 32
      export-datas: [cbpf-net-span,ebpf-sys-span]
      export-data-types: [service_info,tracing_info,network_layer,flow_info,transport_layer,application_layer,metrics]
      export-custom-k8s-labels-regexp:
      export-only-with-traceid: false
      grpc-headers:
```
截图如下：
![image](https://github.com/deepflowio/deepflow/assets/22673808/3aa8f670-1da8-4daa-9434-cbd97edd9fea)

4.保存退出后，执行：
```
kubectl delete pod deepflow-server-8676fdf457-mnplb  -n deepflow
```

5.等待一段时间后，查看pod日志：
```
kubectl logs -f deepflow-server-8676fdf457-kll8k --all-containers=true -n  deepflow

2023-09-12 17:57:29.096 [INFO] [labeler] labeler_manager.go:212 Start labeler manager
2023-09-12 17:57:29.097 [INFO] [trident_adapter] trident_adapter.go:300 Start trident adapter
2023-09-12 17:57:29.097 [ERRO] [flow_log.config] config.go:136 Unmarshal yaml error: yaml: unmarshal errors:
  line 41: cannot unmarshal !!map into []exporter.ExporterCfg
```
如下图所示：
![image](https://github.com/deepflowio/deepflow/assets/22673808/6df8cb01-16e9-42b8-b836-d1eebb46ec82)

### DeepFlow version

deepflow-server version:
```
2023/09/12 17:39:28 ENV K8S_NODE_NAME_FOR_DEEPFLOW=rzy4813; K8S_NODE_IP_FOR_DEEPFLOW=172.21.48.13; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-8676fdf457-mnplb; K8S_POD_IP_FOR_DEEPFLOW=100.68.128.11; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.3.7
CommitID: 7329db5f746f8ecfdcc52645e5cc9d88f02e25f7
RevCount: 8879
Compiler: go version go1.20.7 linux/amd64
CompileTime: 2023-09-01 06:20:52
```

deepflow-agent version:
```
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8879-7329db5f746f8ecfdcc52645e5cc9d88f02e25f7
Name: deepflow-agent community edition
Branch: v6.3.7
CommitId: 7329db5f746f8ecfdcc52645e5cc9d88f02e25f7
RevCount: 8879
Compiler: rustc 1.71.1 (eb26296b5 2023-08-03)
CompileTime: 2023-09-01 06:21:59
```

### DeepFlow agent list

当前
```
curl (http://172.21.48.13:30417/v1/vtaps/) failed, (Get "http://172.21.48.13:30417/v1/vtaps/": dial tcp 172.21.48.13:30417: connect: connection refused)
```

### Kubernetes CNI

calico

### Operation-System/Kernel version

操作系统版本："TencentOS Server 3.1 (Final)"
内核版本："5.4.119-19-0009.11"

### Anything else

pod重启的过程中一直报一个
```
2023-09-12 17:56:29.080 [WARN] [config] watcher.go:110 Can't find my clickhouse endpoint, myNodeName: rzy4813 myPodName: deepflow-server-8676fdf457-kll8k
2023-09-12 17:56:29.083 [WARN] [config] config.go:272 get clickhouse endpoints(deepflow-clickhouse) failed, err: can't find my clickhouse endpoint now, pleate wait later...
```
截图：
![image](https://github.com/deepflowio/deepflow/assets/22673808/8d13c733-a637-4535-9fe5-da70b0886c22)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jiekun** [comment]
Hi. Thanks for interested in OTLP exporter. I am the external contributor who worked with the exporter for a while.
Hi. 感谢你对 OTLP exporter 感兴趣，我是外部的 Contributor，跟 exporter 打交道了一段时间。

The OTLP exporter and exporter interface / implementation are being changed frequently for a few weeks since August.
OTLP exporter 和 exporter 的接口格式 / 具体实现从 8 月起一直在频繁修改，主要为了提供更好的扩展性方便添加新的 exporter。

The config layout you are looking at match the latest code on main branch, which does not fit v6.3.7 (the version you are using).
你正在使用的配置格式对应最新 main 分支上的代码，不适用于 v6.3.7（你在用的 server 版本）

I'm sorry that community doc only provide the latest edition, which might not adapt to the previous releases / tags.
很抱歉社区的文档只提供了最新格式的配置，这些配置格式可能不适用于之前的版本 / tag。

I modified your configuration to the following, and hope it could work:
我简单修改了一下你的配置，希望能 work：
```yaml
ingester:
  exporters:
    - name: your_otlp_exporter_name  # change me. the name is not using for now, but to identify different otlp exporters.
      exporter_type: otlp-exporter
      otlp-exporter:
        enabled: true
        addr: 192.168.42.252:4317
        export-datas: [cbpf-net-span,ebpf-sys-span]
        export-data-types:  [service_info,tracing_info,network_layer,flow_info,transport_layer,application_layer,metrics]
        queue-count: 4
        queue-size: 100000
        export-custom-k8s-labels-regexp:
        export-only-with-traceid: false
        export-batch-count: 32
        grpc-headers:
```

I'm linking you to the related issue and PR, but you don't have to read them all:
以下是 exporter 修改的相关 issue 和 PR，你也不一定需要都去爬楼：
https://github.com/deepflowio/deepflow/pull/3932
https://github.com/deepflowio/deepflow/pull/4050
https://github.com/deepflowio/deepflow/issues/4157
https://github.com/deepflowio/deepflow/pull/4169
https://github.com/deepflowio/deepflow/pull/4177

If you still facing similar issue, one easy way is to check the code under specific tag. For v6.3.7, you can see the exporter config layout here:
如果你还碰到类似的问题，一个简单的方法是看一下对应版本的代码。你可以在这里看到 v6.3.7 的 exporter 配置结构：
https://github.com/deepflowio/deepflow/blob/v6.3.7/server/ingester/flow_log/exporter/config.go

And OTLP exporter config layout here:
以及 OTLP exporter 的配置结构：
https://github.com/deepflowio/deepflow/blob/v6.3.7/server/ingester/flow_log/exporter/otlp_exporter/config.go

-----------------------
As I replying to this issue, I notice that there are a lot of improvement we can do:
回复这个 issue 的时候，我留意到有很多东西可以改进：
1. Version / Tag related documentation. Example: https://skywalking.apache.org/docs/skywalking-go/next/readme/
1. 文档的版本控制，参考：https://skywalking.apache.org/docs/skywalking-go/next/readme/
2. Release note and change log in order to mention BREAKING CHANGE.
3. Release Note 和 Change Log 提醒不兼容的改动。
![image](https://github.com/deepflowio/deepflow/assets/30280396/59195364-9e3c-493e-bb83-e58616eb4202)
    - Example: In OpenTelemetry, a new file to describe what's added/changed is mandatory. Those files in `main` branch will compose the Change Log or Release Note automatically. Writing a PR without description is TERRIBLE.
    - 参考：在 OpenTelemetry 中，需要一个单独的文件来描述改动。这些文件会在发布版本时自动组装成 Change Log，并且清空整个文件夹。提 PR 不写描述的行为时非常糟糕的。
    - .chloggen folder: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/.chloggen
    - .chloggen 目录和文件参考：https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/.chloggen
    - How contributors write change log in PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26479/files#diff-458f9c9480401daba63987f80745e8ecc5d5eac774aa3a8d65ed1d87fc9ae3fb
    - 贡献者是怎样在 PR 附带 Change Log 的：https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26479/files#diff-458f9c9480401daba63987f80745e8ecc5d5eac774aa3a8d65ed1d87fc9ae3fb
