### ISSUE TITLE
[FR] : Load balance of DeepFlow Agent - DeepFlow Server dispatch 

### ISSUE THREAD

**Issue by jiekun** [deepflowio/deepflow#4635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

```sh
deepflow-ctl server ingester list
                        
NAME          IP            REGION   MAX_AGENT_NUM EXP_AGENT_NUM CUR_AGENT_NUM 
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            55            
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            5             
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            7             
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            5             
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            30            
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            4             
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            35            
my.ip.addr.***  my.ip.addr.***  系统默认 200           23            43
```

Currently when agent connect to server with LB, they are not spread evenly. As we could see in the example above, some servers are maintaining 40+ agents, which some are maintaining <= 5 agents.

The CPU / Memory usage of different server pod is not even. For example, some pods use up to 30 GiB memory while others using 5-8 GiB, which make it harder to config the resource limit.

It's expected that agents spread evenly on different server, it should be closed to the **EXP_AGENT_NUM**.

### Use case

N/A

### Related issues

N/A

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SongZhen0704** [comment]
We already support allocating ingester by agent traffic. 
You can configure it in the server.yaml file as needed. 

PR：https://github.com/deepflowio/deepflow/pull/4640

```yaml
ingester-load-balancing-strategy:
  algorithm: by-ingested-data  # 可选值：by-ingested-data、by-agent-count，默认值为 by-ingested-data
  data-duration: 1d            # 以多长时间的数据作为均衡依据
  rebalance-interval: 1h       # 默认每小时重新均衡一次，仅当 algorithm != by-agent-count 时有效
```
