### ISSUE TITLE
[BUG] deepflow-server版本为v6.4.4，集成最新skywalking-oap的版本9.6.0，报错

### ISSUE THREAD

**Issue by cfy3133** [deepflowio/deepflow#4917]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

otel-agent正常连接上skywalking-oap

### How to reproduce

1、docker-compose -f skywalking.yaml执行如下文件安装
内容如下：

```
version: '3.8'
services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: sw #默认创建的数据库
      MYSQL_ROOT_PASSWORD: root #指定用户密码
      MYSQL_PASSWORD: root
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  oap:
    image: apache/skywalking-oap-server:9.6.0
    container_name: oap
    hostname: oap
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 11800:11800 # agent 上报数据的端口，这是 gRPC 端口
      - 12800:12800 # ui 读取数据的端口，这是 http 端口
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      SW_HEALTH_CHECKER: default
      SW_STORAGE: mysql
      SW_JDBC_URL: "jdbc:mysql://mysql:3306/sw?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true"
      SW_DATA_SOURCE_USER: root
      SW_DATA_SOURCE_PASSWORD: root
    volumes:
      #对应上面msyql:8.0.30的版本
      - /opt/soft/mysql-connector-java-8.0.30.jar:/skywalking/oap-libs/mysql-connector-java-8.0.30.jar
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro

  skywaling-ui:
    image: apache/skywalking-ui:9.6.0
    container_name: ui
    restart: always
    hostname: ui
    depends_on:
      - oap
    links:
      - oap
    ports:
      - 28080:8080
    networks:
      - skywalking
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://oap:12800
      SW_HEALTH_CHECKER: default
      SW_TIMEOUT: 200000
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
networks:
  skywalking:
```

![image](https://github.com/deepflowio/deepflow/assets/43978367/ff403c64-eadb-4592-a146-61b3438fa673)

2、使用All-in-One 快速部署方式部署deepflow-server
3、OpenTelemetry 安装
kubectl apply -n open-telemetry -f open-telemetry.yaml
内容如下：

```
apiVersion: v1
kind: Namespace
metadata:
  name: open-telemetry
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  namespace: open-telemetry
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      # add the following config
      skywalking:
        protocols:
          grpc:
            endpoint: 192.168.0.103:11800
          http:
            endpoint: 192.168.0.103:12800
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlphttp:
        traces_endpoint: "http://deepflow-agent.deepflow/api/v1/otel/trace"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 400
        # 25% of limit up to 2G
        spike_limit_mib: 100
        check_interval: 5s
      k8sattributes:
      resource:
        attributes:
        - key: app.host.ip
          from_attribute: k8s.pod.ip
          action: insert
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 165
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces:
          receivers: [otlp, skywalking]
          processors: [k8sattributes, resource, memory_limiter, batch]
          exporters: [otlphttp]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  namespace: open-telemetry
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      containers:
      - command:
          - "/otelcol-contrib"
          - "--config=/conf/otel-agent-config.yaml"
        image: otel/opentelemetry-collector-contrib:0.62.0
        name: otel-agent
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # ZPages endpoint.
        - containerPort: 4317 # Default OpenTelemetry receiver port.
        - containerPort: 4318
        - containerPort: 8888  # Metrics.
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
        - name: timezone
          mountPath: /etc/localtime
      serviceAccountName: opentelemetry-collector
      serviceAccount: opentelemetry-collector
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: Service
metadata:
  name: otel-agent
  namespace: open-telemetry
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  ports:
  - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: otel-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector
  namespace: open-telemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-role-binding
subjects:
- kind: ServiceAccount
  name: opentelemetry-collector
  namespace: open-telemetry
roleRef:
  kind: ClusterRole
  name: otel-collector-role
  apiGroup: rbac.authorization.k8s.io
```

已做修改内容：
![image](https://github.com/deepflowio/deepflow/assets/43978367/536863ac-f28e-40ab-ab47-6671186de3f4)
![image](https://github.com/deepflowio/deepflow/assets/43978367/98ab315b-94f7-450d-be29-d5f3a7df6782)

4、采集器组配置：

```
cat << EOF > agent-group-config.yaml
vtap_group_id: g-c839c86896
external_agent_http_proxy_enabled: 1   # required
external_agent_http_proxy_port: 38086  # optional, default 38086
EOF
```

```
deepflow-ctl agent-group-config create -f agent-group-config.yaml
```

5、重启 otel-agent：

```
kubectl rollout restart -n open-telemetry daemonset/otel-agent
```
查看日志报错：

```
kubectl -n open-telemetry logs pod/otel-agent-fpfcw
```
![image](https://github.com/deepflowio/deepflow/assets/43978367/7d57e9a4-d8a4-481e-811b-1fb717100934)
![image](https://github.com/deepflowio/deepflow/assets/43978367/e3942ebd-435c-4665-bc50-e73e5b0d38f0)

### DeepFlow version

deepflow-server版本为v6.4.4

### Operation-System/Kernel version

Linux master 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
