### ISSUE TITLE
[BUG] deepflow agent对应用性能影响过高

### ISSUE THREAD

**Issue by infra403** [deepflowio/deepflow#5344]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

deepflow agent对于业务的tps、rt影响应该在5%以内

### How to reproduce

测试环境详细信息，参考：https://github.com/baxiaoshi/deepflow-go-demo

### DeepFlow version

v6.3.9

### Kubernetes CNI

calico

### Operation-System/Kernel version

Linux release 7.9.2009 (Core)
内核版本: 5.10.109-1

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by LYootsz** [comment]
你好，请问你的压测工具和deepflow-agent以及redis服务端是否位于同一服务器或节点？

**Comment by LYootsz** [comment]
你好，目前确定了该现象的原因
1. 如果 CPU 到顶了，性能影响可能比较大
2. 如果是通过限制了 Thread 数量，CPU 跑不上去，性能影响可能比较大
推荐在「在给定 TPS 下」测试对 RT 的影响，我们之后会给出这样一个压测工具。

推荐升级到 6.4LTS，deepflow-agent在这个版本性能做了进一步优化，内部测试redis的tps影响降低到了5%。
针对这类应用协议已经开始继续做后续优化。

**Comment by infra403** [comment]
升级到6.4后，在下面的配置下，对应用的tps影响仍然在5%，如果使用默认配置，则在10%以上，使用helm安装后，默认有那些配置是需要调整的吗？
```yaml
vtap_group_id: g-f1bdc6a77d
collector_enabled: 0
l4_log_tap_types:
- -1
l7_log_collect_nps_threshold: 20000
l7_metrics_enabled: 0
l7_log_store_tap_types:
- -1
l4_performance_enabled: 0
static_config:
  ebpf:
    disabled: true
    on-cpu-profile:
      disabled: true
```
