### ISSUE TITLE
[FR] Optimize the configuration method of specified Watcher.

### ISSUE THREAD

**Issue by Hyzhou** [deepflowio/deepflow#5404]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We want to use a set of Agents deployed by Deployment as Kubernetes Watchers.
Now the way to designate an Agent as a Kubernetes Watcher is to configure its IP address and Mac address.
After the rolling update, the configuration will become invalid. We need some other way to point Kubernetes Watcher to a set of workloads.

### Use case

```yaml
name: k8s-d-rrcmIdbEph
type: kubernetes
config:
  controller_ip: 192.168.4.40
  node_port_name_regex: ^(cni|flannel|vxlan.calico|tunl|en[ospx])
  pod_net_ipv4_cidr_max_mask: 16
  pod_net_ipv6_cidr_max_mask: 64
  region_uuid: ffffffff-ffff-ffff-ffff-ffffffffffff
  vtap_id: 192.168.4.46-52:54:00:d5:d0:8e
```

Now, setting the vtap_id by ip and mac. What about a better way to configure this. Stable pointing to a set of workloads.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
