### ISSUE TITLE
[BUG] agent 关闭l7_metrics后ebpf采集不生效

### ISSUE THREAD

**Issue by qyzhaoxun** [deepflowio/deepflow#6006]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

standalone模式下关闭l7_metrics_enabled后agent ebpf采集器也能正常工作

### How to reproduce

deepflow-agent以下述配置文件以standalone模式启动
```
deepflow-agent --standalone -f /etc/deepflow-agent-standalone.yaml
```
配置文件 /etc/deepflow-agent-standalone.yaml
```
collector_socket_type: FILE
static_config:
  l7-protocol-enabled:
  - HTTP
  - HTTP2
  - DNS
  - TLS
  ebpf:
    io-event-collect-mode: 0
    on-cpu-profile:
      disabled: true
l4_performance_enabled: 0
l7_metrics_enabled: 0
```

**配置文件中把l7_metrics_enabled注释后再启动，ebpf采集器就可以正常工作**

### DeepFlow agent list

v6.4

### Kubernetes CNI

deepflow-agent是以hostnetwork方式运行在tke集群上

### Operation-System/Kernel version

"Ubuntu 22.04 LTS"
5.15.0-94-generic

### Anything else

**ebpf collect关闭后没有再启动**
[deepflow-agent-without-l7metrics.log](https://github.com/deepflowio/deepflow/files/14863802/deepflow-agent-without-l7metrics.log)

**ebpf collect关闭后又重新启动**
[deepflow-agent-with-l7-metrics.log](https://github.com/deepflowio/deepflow/files/14863809/deepflow-agent-with-l7-metrics.log)

**另外还有一个疑问，为什么agent都是先attach，再detach，然后再attach，为什么要detach？**

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
