### ISSUE TITLE
[FR] Deepflow 内存占用问题

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [deepflowio/deepflow#7279]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### 1.1. 环境信息

* 两个节点（共 16c24g）
* 每分钟 20w gPRC 请求

#### a. CPU / MEM

**Total: 1.5c5g**（只算了 Server / Agent / CK）

Server
![image](https://github.com/deepflowio/deepflow/assets/42019787/cae4dab1-ee51-4e47-a380-e5aab3e0ca0b)

ClickHouse
![image](https://github.com/deepflowio/deepflow/assets/42019787/35d7e518-2a05-4186-a096-9b470b7dcb74)

Agent
![image](https://github.com/deepflowio/deepflow/assets/42019787/55fd45a9-84fd-40b9-b8f2-08bafd5f3495)

#### b. 存储

![image](https://github.com/deepflowio/deepflow/assets/42019787/2d66c847-a9a9-4d41-a9db-a01f54d553fd)

![image](https://github.com/deepflowio/deepflow/assets/42019787/50a621ee-adac-4fc0-9c30-908823b531b0)

### 1.3 Final

这个集群的业务负载为 **1c1.5g**，Deepflow 的内存占用是业务负载的 3 倍以上

![image](https://github.com/deepflowio/deepflow/assets/42019787/171402b8-5892-4e07-bd8e-fbb8c57f6ade)

为了节约资源，已经修改 Agent 配置，尽可能不采不关注的数据，但最后依然占用整个集群近 25% 的内存。

```yaml
vtap_group_id: xxx
vtap_flow_1s_enabled: 0
capture_bpf: "not (tcp port 4317 or tcp port 12520)"
static_config:
  ebpf:
    # 关闭 Profiling
    on-cpu-profile:
      disabled: true
  l7-protocol-enabled:
    - HTTP2
    - MySQL
    - Redis
    - Kafka
    - MQTT
    - DNS
    - TLS
  # 仅针对指定端口解析指定协议，此处主要是为了过滤掉 Deepflow MySQL 的请求
  l7-protocol-ports:
    "MySQL": "3306"
    "DNS": "53,5353"
```

#### a. CPU / MEM

**Total: 0.6c5g**

![image](https://github.com/deepflowio/deepflow/assets/42019787/5a08a3a4-1125-4758-9545-3112a9b371f3)

#### b. 存储

![image](https://github.com/deepflowio/deepflow/assets/42019787/58619737-f10d-47f3-8633-d073092793d9)

![image](https://github.com/deepflowio/deepflow/assets/42019787/41af5643-d45d-477d-ade8-08dfdaffcbbc)

### 2.2 Final

看起来一个一天记录几个 G 的环境，也需要 5g 左右的内存

## 3. 问题

* Agent 的内存消耗是否有优化空间？：看起来 Agent 至少需要 200～300M 的内存
* 是否有性能分析文档，内存占用分布情况如何，要怎么针对性优化？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
