### ISSUE TITLE
[FR] HTTP支持解析headers里面的字段信息吗

### ISSUE THREAD

**Issue by midorifizz** [deepflowio/deepflow#7800]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我想在 l7_flow_log 中针对 http 协议进行进一步的解析，需要提取 headers 中的某些字段。看代码发现目前 http request 解析了method，path字段，response解析了status_code，result信息，好像并没有看到 headers。请问有相关的设置能够采集到 http headers 信息吗，还是说需要自己改代码支持，如果需要改代码支持的话，可否给出需要修改的文件，不胜感激。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L1197

```yaml
    # Configuration to extract the customized header fields of HTTP, HTTP2, GRPC protocol etc
    extra-log-fields:
    # for example:
    # http:
    # - field-name: "user-agent"
    # - field-name: "cookie"
      http: []
      http2: []
```

可以按此配置，提取字段。

参考博客：https://www.deepflow.io/blog/zh/065-autotracing-supports-brpc-enhance-grpc-dubbo-http/#0x3-%E6%94%AF%E6%8C%81%E8%87%AA%E5%AE%9A%E4%B9%89%E9%87%87%E9%9B%86-HTTP-x2F-HTTP2-%E5%A4%B4%E5%AD%97%E6%AE%B5
