### ISSUE TITLE
[BUG] vtap表中出现重复的lcuuid

### ISSUE THREAD

**Issue by asdfsx** [deepflowio/deepflow#7817]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

在mysql的vtap表中，发现了lcuuid重复的数据。
![image](https://github.com/user-attachments/assets/d5bd304e-bfb0-4e5e-aa53-af6fbdd287cc)
暂时不知道重复的的lcuuid会对什么操作造成影响，但是猜测会不会对探针enable/disable、探针状态更新造成一定的影响。

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，你能通过`deepflow-ctl agent list`看一下目前 agent 的状态，以及能否导出一份 `select * from deepflow.vtap` 的数据

**Comment by asdfsx** [comment]
agent 状态如下，id 3、5 两条记录的lcuuid是一样的。

```
# deepflow-ctl agent list
ID   NAME            TYPE       CTRL_IP        CTRL_MAC            STATE     GROUP     EXCEPTIONS   REVISION       UPGRADE_REVISION
2    haiguang01-W1   CHOST_VM   192.168.9.39   80:61:5f:12:b5:76   DISABLE   default                v6.6.1 10797
3    master1-W2      CHOST_VM   192.168.9.66   5a:0f:a9:de:67:19   DISABLE   default                v6.6.1 10797
5    master1-W2      CHOST_VM   192.168.9.67   46:5e:ee:17:c6:3a   NORMAL    default                v6.6.1 10797
```

目前数据库里只有3条记录。另外是依据什么规则创建的？

```
mysql> select * from vtap \G;
*************************** 1. row ***************************
                  id: 2
                name: haiguang01-W1
        raw_hostname: haiguang01
               state: 1
              enable: 0
                type: 3
             ctrl_ip: 192.168.9.39
            ctrl_mac: 80:61:5f:12:b5:76
             tap_mac:
         analyzer_ip: 192.168.9.178
     cur_analyzer_ip: 192.168.9.178
       controller_ip: 192.168.9.178
   cur_controller_ip: 192.168.9.178
       launch_server: 192.168.9.39
    launch_server_id: 1
                  az: ce6708ef-78eb-53b4-956b-ea43631fcf43
              region: ffffffff-ffff-ffff-ffff-ffffffffffff
            revision: v6.6.1 10797-6eb9865fee448337a54b71e8e260318005c1669f
synced_controller_at: 2024-08-14 14:33:37
  synced_analyzer_at: 2024-08-14 14:39:39
          created_at: 2024-08-13 17:19:38
           boot_time: 1723601582
          exceptions: 0
         vtap_lcuuid:
   vtap_group_lcuuid: 7b09c74d-5923-11ef-83ff-0242c0a82003
             cpu_num: 96
         memory_size: 270346215424
                arch: x86_64
                  os: Anolis OS 8.6
      kernel_version: 5.11.0-csv
        process_name: deepflow-agent-ce
   current_k8s_image:
        license_type: 1
   license_functions: 2,3,4,5,6,8
            tap_mode: 0
             team_id: 1
   expected_revision:
     upgrade_package:
              lcuuid: 7d5a48bc-34aa-5010-b944-929962bc8b32
*************************** 2. row ***************************
                  id: 3
                name: master1-W2
        raw_hostname: master1
               state: 0
              enable: 0
                type: 3
             ctrl_ip: 192.168.9.66
            ctrl_mac: 5a:0f:a9:de:67:19
             tap_mac:
         analyzer_ip: 192.168.9.178
     cur_analyzer_ip: 192.168.9.178
       controller_ip: 192.168.9.178
   cur_controller_ip: 192.168.9.178
       launch_server: 192.168.9.66
    launch_server_id: 2
                  az: ce6708ef-78eb-53b4-956b-ea43631fcf43
              region: ffffffff-ffff-ffff-ffff-ffffffffffff
            revision: v6.6.1 10797-6eb9865fee448337a54b71e8e260318005c1669f
synced_controller_at: 2024-08-15 13:13:35
  synced_analyzer_at: 2024-08-15 13:18:41
          created_at: 2024-08-15 13:13:35
           boot_time: 1723698720
          exceptions: 0
         vtap_lcuuid:
   vtap_group_lcuuid: 7b09c74d-5923-11ef-83ff-0242c0a82003
             cpu_num: 16
         memory_size: 33564733440
                arch: x86_64
                  os: CentOS Linux 7
      kernel_version: 3.10.0-1160.118.1.el7.x86_64
        process_name: deepflow-agent-ce
   current_k8s_image:
        license_type: 1
   license_functions: 2,3,4,5,6,8
            tap_mode: 0
             team_id: 1
   expected_revision:
     upgrade_package:
              lcuuid: b4325d95-6917-5294-a6a3-f93ca9d18135
*************************** 3. row ***************************
                  id: 5
                name: master1-W2
        raw_hostname: master1
               state: 1
              enable: 1
                type: 3
             ctrl_ip: 192.168.9.67
            ctrl_mac: 46:5e:ee:17:c6:3a
             tap_mac:
         analyzer_ip: 192.168.9.178
     cur_analyzer_ip: 192.168.9.178
       controller_ip: 192.168.9.178
   cur_controller_ip: 192.168.9.178
       launch_server: 192.168.9.67
    launch_server_id: 2
                  az: ce6708ef-78eb-53b4-956b-ea43631fcf43
              region: ffffffff-ffff-ffff-ffff-ffffffffffff
            revision: v6.6.1 10797-6eb9865fee448337a54b71e8e260318005c1669f
synced_controller_at: 2024-08-15 15:37:42
  synced_analyzer_at: 2024-08-15 15:37:36
          created_at: 2024-08-15 15:33:41
           boot_time: 1723707126
          exceptions: 0
         vtap_lcuuid:
   vtap_group_lcuuid: 7b09c74d-5923-11ef-83ff-0242c0a82003
             cpu_num: 16
         memory_size: 33564733440
                arch: x86_64
                  os: CentOS Linux 7
      kernel_version: 3.10.0-1160.118.1.el7.x86_64
        process_name: deepflow-agent-ce
   current_k8s_image:
        license_type: 1
   license_functions: 2,3,4,5,6,8
            tap_mode: 0
             team_id: 1
   expected_revision:
     upgrade_package:
              lcuuid: b4325d95-6917-5294-a6a3-f93ca9d18135
3 rows in set (0.00 sec)
```
