### ISSUE TITLE
[BUG] "trident-type-for-unkonw-vtap" in legacy agent documentation

### ISSUE THREAD

**Issue by Unprincess17** [deepflowio/deepflow#8303]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Docs

### What you expected to happen

There is a typo in [legacy server](https://deepflow.io/docs/ce-install/legacy-host/) documentation:
```yaml
configmap:
  server.yaml:
    controller:
      genesis:
        local_ip_ranges:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          - 169.254.0.0/15
          - 224.0.0.0-240.255.255.255
          - 100.42.32.0/24 # FIXME
      trisolaris:
        trident-type-for-unkonw-vtap: 3 # required
```
The `trident-type-for-unkonw-vtap` should be `trident-type-for-unknow-vtap`
![{DDD898C7-CA2E-4D14-9E0B-656F7959BED2}](https://github.com/user-attachments/assets/d08e1f65-bea1-43dc-bea9-805b6b266624)
```bash
$ grep trident-type server.log
  trident-type-for-unknow-vtap: 3
```

### How to reproduce

https://deepflow.io/docs/ce-install/legacy-host/

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.6.6
CommitID: d5e26dd2618cf3dbac2c10594d06d75aab3a38e1
RevCount: 11227
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-10-11 05:20:20

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
