### ISSUE TITLE
Unable to discover simple web-service

### ISSUE THREAD

**Issue by gijs-blanken** [deepflowio/deepflow#9392]
Hi DeepFlow team!

I'm masters student at Utrecht University currently writing my thesis on distributed service mapping and I wanted to include DeepFlow in my comparisons. I managed to get the software running across 3 nodes but I'm unable to find my simple webserver in one of the "maps" in Grafana. 

I would expect to this network interaction in the 'Network - K8s Pod Map' grafana board. I've attached a view of both the client and server panel.

<img width="1476" alt="Image" src="https://github.com/user-attachments/assets/73f3714b-9ce4-4631-9ab5-81d0bd7cecde" />

<img width="1473" alt="Image" src="https://github.com/user-attachments/assets/6a358cdf-7f7a-4869-bc8c-533fe8d79ee0" />

And here is the configuration for the simple webservice.

<details>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: python-webserver-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: python-webserver
  namespace: python-webserver-ns
  labels:
    app: python-webserver
spec:
  # Pin this Pod to the first node
  nodeName: ip-172-31-18-196
  containers:
    - name: python-webserver
      image: python:3.9-slim
      command: ["python", "-m", "http.server", "8080", "--bind", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: python-web-svc
  namespace: python-webserver-ns
spec:
  selector:
    app: python-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-client-script
  namespace: python-webserver-ns
data:
  client.py: |
    import time
    import requests

    url = "http://python-web-svc:8080"
    s = requests.Session()

    while True:
        try:
            response = s.get(url)
            print("Status Code:", response.status_code)
            print("Response Body:", response.text)
        except Exception as e:
            print("Error during request:", e)
        time.sleep(4)
---
apiVersion: v1
kind: Pod
metadata:
  name: python-client
  namespace: python-webserver-ns
  labels:
    app: python-client
spec:
  # Pin this Pod to the second node
  nodeName: ip-172-31-31-211
  restartPolicy: Never
  containers:
    - name: python-client
      image: python:3.9-slim
      command: ["sh", "-c", "pip install requests && python -u /scripts/client.py"]
      volumeMounts:
        - name: script-volume
          mountPath: /scripts
  volumes:
    - name: script-volume
      configMap:
        name: python-client-script

```

</details>

I'd love to compare DeepFlow to my solution!

Thanks in advance,
Gijs
