### ISSUE TITLE
[FR] 希望能支持Zipkin作为外部APM

### ISSUE THREAD

**Issue by bxYu** [deepflowio/deepflow#9800]
### Search before asking

- [x] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

## 背景
我的调用链数据产生自OpenTelemetry Collector，格式是otlp，并通过Skywalking接收，最终存储在Elasticsearch中的格式协议为 **Zipkin V2**（而非Skywalking自身的协议）。

## 诉求
所以希望deepflow在实现外部APM时，能支持Skywalking中**Zipkin v2**格式的调用链数据

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，此处的需求描述的不是很清楚，你们现在是需要把外部数据导入 DeepFlow，还是需要把 DeepFlow 数据导出给 Skywalking？

1. 把 otel 数据导给 sky，这步你们是怎么做的
2. DeepFlow 本身支持 otel 数据的导入，直接发一份过来就行：

  - https://www.deepflow.io/docs/zh/integration/input/tracing/opentelemetry/

**Comment by bxYu** [comment]
1、我们的目的是使用 [调用链补全接口](https://www.deepflow.io/docs/zh/integration/output/query/trace-completion/) ，将 sw 作为外部 APM 来补全 deepflow 系统层/网络层调用链
2、我们已经把数据通过 otel 导出至 sw ，配置如下：
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:xxx
exporters:
  otlp:
    endpoint: xxx-skywalkingoap:11800
    tls:
      insecure: true
    compression: none
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 25
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter]
      exporters: [otlp]
```

3、我们也尝试了将 otel 数据导入至 deepflow ，现状为：只能将 otel 的应用层 span 关联 deepflow 中部分系统层/网络层 span（例如进程/网卡 span），但无法关联 deepflow 中 DNS 类型的 span
