### ISSUE TITLE
[BUG] DeepflowV7版本如何接收Opentelemetry Collector的Trace数据？

### ISSUE THREAD

**Issue by ZhiLiGod** [deepflowio/deepflow#9954]
### Search before asking

- [x] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

您好，

我在用DeepflowV7版本对接Opentelemetry Collector传过来的数据。
当前的架构为：业务服务集成javaagent -> Otel Collector -> Deepflow Agent -> Deepflow Server。

在对接过程中，参考官网的方法发现已经行不通了 https://deepflow.io/docs/zh/integration/input/tracing/opentelemetry/，应该是由于版本升级的原因，agent-group-config的配置格式发生变化，下面是我按example精简的配置：
```
inputs:
  integration:
    enabled: true # upgrade_from: external_agent_http_proxy_enabled
    listen_port: 38086 # upgrade_from: external_agent_http_proxy_port
```

Opentelemetry Collector的配置：
```
config:
  exporters:
    otlp:
      endpoint: "tempo-distributed-distributor.infra:4317"
      tls:
        insecure: true
    otlphttp:
      traces_endpoint: 'http://deepflow-agent.infra:38086/api/v1/otel/trace'
      tls:
        insecure: true
```
上面是之前使用的grafana-tempo的配置，下面是deepflow-agent的配置，上面的是明确没有问题能看到trace数据的
在traces的配置中，也指明了使用http方式
```
traces: 
      processors:
        - k8sattributes
        - resource
        - memory_limiter
        - batch
      receivers:
        - otlp
      exporters:
        - otlphttp
```
在k8s部署运行后，在deepflow的trace面板，完全看不到来自Otel的trace数据，即使是来自deepflow自己通过ebpf采集的，也没有traceid

![Image](https://github.com/user-attachments/assets/f489e2d9-2cff-4502-8324-685598b550f7)

### DeepFlow version

v7

### DeepFlow agent list

deepflow也手动开了38086的端口
```
deepflow-agent                                     ClusterIP   10.233.10.207   <none>        80/TCP,38086/TCP
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)
